version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskmanager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d taskmanager"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/taskmanager?sslmode=disable"
    ports:
      - "8080:8080"
    volumes:
      - ./backend/templates:/app/templates       # Hot-reload templates
      - ./frontend/static:/app/frontend/static  # Hot-reload static files

volumes:
  postgres_data: